import type { Program } from '../../domain/programs/Program.js';

export const programs: Program[] = [
  {
    id: 'football',
    title: 'Футбол',
    category: 'sport',
    capacity: 16,
    enrolledCount: 14,
    status: 'open',
    leaderIds: [],
    updatedAt: '2026-09-18T09:25:00+07:00',
  },
  {
    id: 'swimming',
    title: 'Плавание',
    category: 'sport',
    capacity: 10,
    enrolledCount: 9,
    status: 'open',
    leaderIds: [],
    updatedAt: '2026-09-18T09:25:00+07:00',
  },
  {
    id: 'robotics',
    title: 'Робототехника',
    category: 'other',
    capacity: 16,
    enrolledCount: 14,
    status: 'open',
    leaderIds: [],
    updatedAt: '2026-09-18T09:25:00+07:00',
  },
  {
    id: 'programming',
    title: 'Программирование',
    category: 'other',
    capacity: 12,
    enrolledCount: 17,
    status: 'open',
    leaderIds: [],
    updatedAt: '2026-09-18T09:25:00+07:00',
  },
  {
    id: 'vocal',
    title: 'Вокал',
    category: 'other',
    capacity: 15,
    enrolledCount: 7,
    status: 'open',
    leaderIds: [],
    updatedAt: '2026-09-18T09:25:00+07:00',
  },
];